// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9ewthDdft9qWK6bn4r1FB0GCGhgYq_T8',
    appId: '1:791539468122:web:8a00d594af584ddc9b1563',
    messagingSenderId: '791539468122',
    projectId: 'vikrantebike',
    authDomain: 'vikrantebike.firebaseapp.com',
    databaseURL: 'https://vikrantebike-default-rtdb.firebaseio.com',
    storageBucket: 'vikrantebike.firebasestorage.app',
    measurementId: 'G-KFLWELJQ5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOOJemgqsv625hV72JSm1j99BIbGi0WM0',
    appId: '1:791539468122:android:73349f488cfd6a8b9b1563',
    messagingSenderId: '791539468122',
    projectId: 'vikrantebike',
    databaseURL: 'https://vikrantebike-default-rtdb.firebaseio.com',
    storageBucket: 'vikrantebike.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj-jaejfRk4h64CAlkkczMtLN2zEClkwU',
    appId: '1:791539468122:ios:3f88169dec2c22929b1563',
    messagingSenderId: '791539468122',
    projectId: 'vikrantebike',
    databaseURL: 'https://vikrantebike-default-rtdb.firebaseio.com',
    storageBucket: 'vikrantebike.firebasestorage.app',
    iosBundleId: 'com.example.vikrant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj-jaejfRk4h64CAlkkczMtLN2zEClkwU',
    appId: '1:791539468122:ios:3f88169dec2c22929b1563',
    messagingSenderId: '791539468122',
    projectId: 'vikrantebike',
    databaseURL: 'https://vikrantebike-default-rtdb.firebaseio.com',
    storageBucket: 'vikrantebike.firebasestorage.app',
    iosBundleId: 'com.example.vikrant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9ewthDdft9qWK6bn4r1FB0GCGhgYq_T8',
    appId: '1:791539468122:web:8580a8b9304e254d9b1563',
    messagingSenderId: '791539468122',
    projectId: 'vikrantebike',
    authDomain: 'vikrantebike.firebaseapp.com',
    databaseURL: 'https://vikrantebike-default-rtdb.firebaseio.com',
    storageBucket: 'vikrantebike.firebasestorage.app',
    measurementId: 'G-BPW9SNZ0VY',
  );
}
